// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

public interface bridgeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.bridgeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *streams the number of pedestrians on the bridge.
   * </pre>
   *
   * <code>int32 pedestrianCount = 1;</code>
   */
  int getPedestrianCount();
}
