// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

public interface bridgeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.bridgeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *streams whether or not the bridge is using energy harvesting or grid supply.
   * </pre>
   *
   * <code>string energyStatus = 1;</code>
   */
  java.lang.String getEnergyStatus();
  /**
   * <pre>
   *streams whether or not the bridge is using energy harvesting or grid supply.
   * </pre>
   *
   * <code>string energyStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getEnergyStatusBytes();
}
