// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

/**
 * Protobuf type {@code EnergyEfficiency.bridgeMessage}
 */
public  final class bridgeMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnergyEfficiency.bridgeMessage)
    bridgeMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use bridgeMessage.newBuilder() to construct.
  private bridgeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private bridgeMessage() {
    pedestrianCount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private bridgeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pedestrianCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_bridgeMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_bridgeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.examples.EnergyEfficiency.bridgeMessage.class, ds.examples.EnergyEfficiency.bridgeMessage.Builder.class);
  }

  public static final int PEDESTRIANCOUNT_FIELD_NUMBER = 1;
  private int pedestrianCount_;
  /**
   * <pre>
   *streams the number of pedestrians on the bridge.
   * </pre>
   *
   * <code>int32 pedestrianCount = 1;</code>
   */
  public int getPedestrianCount() {
    return pedestrianCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pedestrianCount_ != 0) {
      output.writeInt32(1, pedestrianCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pedestrianCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pedestrianCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.examples.EnergyEfficiency.bridgeMessage)) {
      return super.equals(obj);
    }
    ds.examples.EnergyEfficiency.bridgeMessage other = (ds.examples.EnergyEfficiency.bridgeMessage) obj;

    boolean result = true;
    result = result && (getPedestrianCount()
        == other.getPedestrianCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PEDESTRIANCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPedestrianCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.bridgeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.examples.EnergyEfficiency.bridgeMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnergyEfficiency.bridgeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnergyEfficiency.bridgeMessage)
      ds.examples.EnergyEfficiency.bridgeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_bridgeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_bridgeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.examples.EnergyEfficiency.bridgeMessage.class, ds.examples.EnergyEfficiency.bridgeMessage.Builder.class);
    }

    // Construct using ds.examples.EnergyEfficiency.bridgeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pedestrianCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_bridgeMessage_descriptor;
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.bridgeMessage getDefaultInstanceForType() {
      return ds.examples.EnergyEfficiency.bridgeMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.bridgeMessage build() {
      ds.examples.EnergyEfficiency.bridgeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.bridgeMessage buildPartial() {
      ds.examples.EnergyEfficiency.bridgeMessage result = new ds.examples.EnergyEfficiency.bridgeMessage(this);
      result.pedestrianCount_ = pedestrianCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.examples.EnergyEfficiency.bridgeMessage) {
        return mergeFrom((ds.examples.EnergyEfficiency.bridgeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.examples.EnergyEfficiency.bridgeMessage other) {
      if (other == ds.examples.EnergyEfficiency.bridgeMessage.getDefaultInstance()) return this;
      if (other.getPedestrianCount() != 0) {
        setPedestrianCount(other.getPedestrianCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.examples.EnergyEfficiency.bridgeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.examples.EnergyEfficiency.bridgeMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pedestrianCount_ ;
    /**
     * <pre>
     *streams the number of pedestrians on the bridge.
     * </pre>
     *
     * <code>int32 pedestrianCount = 1;</code>
     */
    public int getPedestrianCount() {
      return pedestrianCount_;
    }
    /**
     * <pre>
     *streams the number of pedestrians on the bridge.
     * </pre>
     *
     * <code>int32 pedestrianCount = 1;</code>
     */
    public Builder setPedestrianCount(int value) {
      
      pedestrianCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *streams the number of pedestrians on the bridge.
     * </pre>
     *
     * <code>int32 pedestrianCount = 1;</code>
     */
    public Builder clearPedestrianCount() {
      
      pedestrianCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EnergyEfficiency.bridgeMessage)
  }

  // @@protoc_insertion_point(class_scope:EnergyEfficiency.bridgeMessage)
  private static final ds.examples.EnergyEfficiency.bridgeMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.examples.EnergyEfficiency.bridgeMessage();
  }

  public static ds.examples.EnergyEfficiency.bridgeMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bridgeMessage>
      PARSER = new com.google.protobuf.AbstractParser<bridgeMessage>() {
    @java.lang.Override
    public bridgeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new bridgeMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<bridgeMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bridgeMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.examples.EnergyEfficiency.bridgeMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

