// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public interface hydroRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.hydroRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hydro = 1;</code>
   */
  java.lang.String getHydro();
  /**
   * <code>string hydro = 1;</code>
   */
  com.google.protobuf.ByteString
      getHydroBytes();
}
