// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public interface hydroResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.hydroResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hydroStatus = 1;</code>
   */
  java.lang.String getHydroStatus();
  /**
   * <code>string hydroStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getHydroStatusBytes();
}
