// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

/**
 * <pre>
 *streams the lumens values back to the client.
 * </pre>
 *
 * Protobuf type {@code EnergyEfficiency.lightResponse}
 */
public  final class lightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnergyEfficiency.lightResponse)
    lightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lightResponse.newBuilder() to construct.
  private lightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lightResponse() {
    numbers_ = 0;
    lightStatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            numbers_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lightStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_lightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_lightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.examples.EnergyEfficiency.lightResponse.class, ds.examples.EnergyEfficiency.lightResponse.Builder.class);
  }

  public static final int NUMBERS_FIELD_NUMBER = 1;
  private int numbers_;
  /**
   * <code>int32 numbers = 1;</code>
   */
  public int getNumbers() {
    return numbers_;
  }

  public static final int LIGHTSTATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object lightStatus_;
  /**
   * <code>string lightStatus = 2;</code>
   */
  public java.lang.String getLightStatus() {
    java.lang.Object ref = lightStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lightStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string lightStatus = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLightStatusBytes() {
    java.lang.Object ref = lightStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lightStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numbers_ != 0) {
      output.writeInt32(1, numbers_);
    }
    if (!getLightStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lightStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numbers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numbers_);
    }
    if (!getLightStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lightStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.examples.EnergyEfficiency.lightResponse)) {
      return super.equals(obj);
    }
    ds.examples.EnergyEfficiency.lightResponse other = (ds.examples.EnergyEfficiency.lightResponse) obj;

    boolean result = true;
    result = result && (getNumbers()
        == other.getNumbers());
    result = result && getLightStatus()
        .equals(other.getLightStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
    hash = (53 * hash) + getNumbers();
    hash = (37 * hash) + LIGHTSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getLightStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.examples.EnergyEfficiency.lightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.examples.EnergyEfficiency.lightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *streams the lumens values back to the client.
   * </pre>
   *
   * Protobuf type {@code EnergyEfficiency.lightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnergyEfficiency.lightResponse)
      ds.examples.EnergyEfficiency.lightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_lightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_lightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.examples.EnergyEfficiency.lightResponse.class, ds.examples.EnergyEfficiency.lightResponse.Builder.class);
    }

    // Construct using ds.examples.EnergyEfficiency.lightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      numbers_ = 0;

      lightStatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.examples.EnergyEfficiency.Service1ElectricityImpl.internal_static_EnergyEfficiency_lightResponse_descriptor;
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.lightResponse getDefaultInstanceForType() {
      return ds.examples.EnergyEfficiency.lightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.lightResponse build() {
      ds.examples.EnergyEfficiency.lightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.examples.EnergyEfficiency.lightResponse buildPartial() {
      ds.examples.EnergyEfficiency.lightResponse result = new ds.examples.EnergyEfficiency.lightResponse(this);
      result.numbers_ = numbers_;
      result.lightStatus_ = lightStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.examples.EnergyEfficiency.lightResponse) {
        return mergeFrom((ds.examples.EnergyEfficiency.lightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.examples.EnergyEfficiency.lightResponse other) {
      if (other == ds.examples.EnergyEfficiency.lightResponse.getDefaultInstance()) return this;
      if (other.getNumbers() != 0) {
        setNumbers(other.getNumbers());
      }
      if (!other.getLightStatus().isEmpty()) {
        lightStatus_ = other.lightStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.examples.EnergyEfficiency.lightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.examples.EnergyEfficiency.lightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int numbers_ ;
    /**
     * <code>int32 numbers = 1;</code>
     */
    public int getNumbers() {
      return numbers_;
    }
    /**
     * <code>int32 numbers = 1;</code>
     */
    public Builder setNumbers(int value) {
      
      numbers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numbers = 1;</code>
     */
    public Builder clearNumbers() {
      
      numbers_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object lightStatus_ = "";
    /**
     * <code>string lightStatus = 2;</code>
     */
    public java.lang.String getLightStatus() {
      java.lang.Object ref = lightStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lightStatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLightStatusBytes() {
      java.lang.Object ref = lightStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lightStatus = 2;</code>
     */
    public Builder setLightStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lightStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lightStatus = 2;</code>
     */
    public Builder clearLightStatus() {
      
      lightStatus_ = getDefaultInstance().getLightStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string lightStatus = 2;</code>
     */
    public Builder setLightStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lightStatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EnergyEfficiency.lightResponse)
  }

  // @@protoc_insertion_point(class_scope:EnergyEfficiency.lightResponse)
  private static final ds.examples.EnergyEfficiency.lightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.examples.EnergyEfficiency.lightResponse();
  }

  public static ds.examples.EnergyEfficiency.lightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lightResponse>
      PARSER = new com.google.protobuf.AbstractParser<lightResponse>() {
    @java.lang.Override
    public lightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.examples.EnergyEfficiency.lightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

