// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

public interface lightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.lightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numbers = 1;</code>
   */
  int getNumbers();

  /**
   * <code>string lightStatus = 2;</code>
   */
  java.lang.String getLightStatus();
  /**
   * <code>string lightStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightStatusBytes();
}
