// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Electricity.proto

package ds.examples.EnergyEfficiency;

public final class Service1ElectricityImpl {
  private Service1ElectricityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_lightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_lightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_lightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_lightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_bridgeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_bridgeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_bridgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_bridgeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Service1Electricity.proto\022\020EnergyEffic" +
      "iency\"9\n\014lightRequest\022\017\n\007numbers\030\001 \001(\005\022\013" +
      "\n\003min\030\002 \001(\005\022\013\n\003max\030\003 \001(\005\"5\n\rlightRespons" +
      "e\022\017\n\007numbers\030\001 \001(\005\022\023\n\013lightStatus\030\002 \001(\t\"" +
      "(\n\rbridgeMessage\022\027\n\017pedestrianCount\030\001 \001(" +
      "\005\"&\n\016bridgeResponse\022\024\n\014energyStatus\030\001 \001(" +
      "\t2\302\001\n\023Service1Electricity\022R\n\013lightSensor" +
      "\022\036.EnergyEfficiency.lightRequest\032\037.Energ" +
      "yEfficiency.lightResponse\"\0000\001\022W\n\014bridgeL" +
      "ights\022\037.EnergyEfficiency.bridgeMessage\032 " +
      ".EnergyEfficiency.bridgeResponse\"\000(\0010\001B9" +
      "\n\034ds.examples.EnergyEfficiencyB\027Service1" +
      "ElectricityImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnergyEfficiency_lightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnergyEfficiency_lightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_lightRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_EnergyEfficiency_lightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnergyEfficiency_lightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_lightResponse_descriptor,
        new java.lang.String[] { "Numbers", "LightStatus", });
    internal_static_EnergyEfficiency_bridgeMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnergyEfficiency_bridgeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_bridgeMessage_descriptor,
        new java.lang.String[] { "PedestrianCount", });
    internal_static_EnergyEfficiency_bridgeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EnergyEfficiency_bridgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_bridgeResponse_descriptor,
        new java.lang.String[] { "EnergyStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
