// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public final class Service2RenewablesImpl {
  private Service2RenewablesImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_turbineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_turbineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_turbineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_turbineResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Service2Renewables.proto\022\020EnergyEffici" +
      "ency\"!\n\016turbineRequest\022\017\n\007turbine\030\001 \001(\t\"" +
      "(\n\017turbineResponse\022\025\n\rturbineStatus\030\001 \001(" +
      "\t2l\n\022Service2Renewables\022V\n\rturbineStatus" +
      "\022 .EnergyEfficiency.turbineRequest\032!.Ene" +
      "rgyEfficiency.turbineResponse\"\000B8\n\034ds.ex" +
      "amples.EnergyEfficiencyB\026Service2Renewab" +
      "lesImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnergyEfficiency_turbineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnergyEfficiency_turbineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_turbineRequest_descriptor,
        new java.lang.String[] { "Turbine", });
    internal_static_EnergyEfficiency_turbineResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnergyEfficiency_turbineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_turbineResponse_descriptor,
        new java.lang.String[] { "TurbineStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
