// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public final class Service2RenewablesImpl {
  private Service2RenewablesImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_turbineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_turbineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_turbineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_turbineResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_NumberMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyEfficiency_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyEfficiency_CalculateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Service2Renewables.proto\022\020EnergyEffici" +
      "ency\"!\n\016turbineRequest\022\017\n\007turbine\030\001 \001(\t\"" +
      "(\n\017turbineResponse\022\025\n\rturbineStatus\030\001 \001(" +
      "\t\"\037\n\rNumberMessage\022\016\n\006number\030\001 \001(\002\"4\n\021Ca" +
      "lculateResponse\022\016\n\006result\030\001 \001(\002\022\017\n\007messa" +
      "ge\030\002 \001(\t2\314\001\n\022Service2Renewables\022V\n\rturbi" +
      "neStatus\022 .EnergyEfficiency.turbineReque" +
      "st\032!.EnergyEfficiency.turbineResponse\"\000\022" +
      "^\n\022hydroAverageValues\022\037.EnergyEfficiency" +
      ".NumberMessage\032#.EnergyEfficiency.Calcul" +
      "ateResponse\"\000(\001B8\n\034ds.examples.EnergyEff" +
      "iciencyB\026Service2RenewablesImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnergyEfficiency_turbineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnergyEfficiency_turbineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_turbineRequest_descriptor,
        new java.lang.String[] { "Turbine", });
    internal_static_EnergyEfficiency_turbineResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnergyEfficiency_turbineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_turbineResponse_descriptor,
        new java.lang.String[] { "TurbineStatus", });
    internal_static_EnergyEfficiency_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnergyEfficiency_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_EnergyEfficiency_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EnergyEfficiency_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyEfficiency_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
