// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public interface turbineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.turbineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string turbineStatus = 1;</code>
   */
  java.lang.String getTurbineStatus();
  /**
   * <code>string turbineStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getTurbineStatusBytes();
}
