// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Renewables.proto

package ds.examples.EnergyEfficiency;

public interface turbineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyEfficiency.turbineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string turbine = 1;</code>
   */
  java.lang.String getTurbine();
  /**
   * <code>string turbine = 1;</code>
   */
  com.google.protobuf.ByteString
      getTurbineBytes();
}
